# Generated by Django 4.2.13 on 2024-06-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='Paid',
            new_name='paid',
        ),
    ]
