# Generated by Django 4.2.13 on 2024-06-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trn_number',
        ),
    ]
